# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cadf836c0b52837d3f0805f2f8e3a95db2a3e298eccdb27893e14f241c4dff18aafd84efe63507e042d681b6751025c8b81c107db5683f936ae621a9091379d

test:
  secret_key_base: d41be03703b278a57718cb260c3c08f1086ad8558a4deda3d42ddce4d67463e3a7373901de5bb1f667904f02b9d2a2bfd066f826c08b73b3375168132d00e0ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
